### ISSUE TITLE
Custom Work

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [lincf0912/LFImagePickerController#19]
Can I hire you to modify this code for a personal project? If yes, then let me know your email so I can send you what I want to do.

**Comment by lincf0912** [comment]
about LFImagePickerController?

**Comment by MarcAnthonyPhotography** [comment]
Yes. This one (https://github.com/lincf0912/LFImagePickerController). I am attaching my version. I only changed a couple things on view controller. Here's what I am looking for.

1. In viewcontroller I added a textfield and an "enter" button. I want to be able to type an album name in the text field. Then, when I press the enter button, it opens the image picker with only that album.

2. I want to be able to select multiple videos. And I would like to select videos and photos at the same time. I don't need to compress video. I simply want to select them and then, when I press done, it logs the path to the selections in NSLog. I am going to add this into my own project later. I just need to have the path to the array shown in a log.

3. I would like to be able to edit videos with text, drawing, and stickers like you can with GIF and photos.

4. I would like the app to work in portrait and landscape. ImagePicker works in both but when you go to edit a photo or gif, it goes to portrait mode.
[ImagePicker2.zip](https://github.com/lincf0912/LFImagePickerController/files/1140847/ImagePicker2.zip)

**Comment by lincf0912** [comment]
1. The next version is available.
2. The next version is available. But the video will only call back NSData, you need to save to the custom path.
3. Video not supported for editing, follow LFMediaEditingController next version is available.
4. This problem has been bothering me for a long time, temporarily unable to realize.
5. This is too special. You can only modify the source code.
Next release, I can give you a Demo, but does not contain 3、4.

**Comment by lincf0912** [comment]
I hope this demo will meet your needs.
[ImagePicker2.zip](https://github.com/lincf0912/LFImagePickerController/files/1147528/ImagePicker2.zip)

**Comment by MarcAnthonyPhotography** [comment]
I am speechless. Thank you so much. I wasn't expecting that. The only other things I would love (for next release) would be editing video and horizontal orientation for editing. Please let me know how much you would charge for those options.

**Comment by lincf0912** [comment]
Hello. editing video has been available. But edit UI can not be compatible with horizontal, because the media can be edited many times. I think it can't be solved in a short time, I'm sorry。Anyway, thank you for your needs.
[ImagePicker2_videoEdit.zip](https://github.com/lincf0912/LFImagePickerController/files/1186234/ImagePicker2_videoEdit.zip)

**Comment by MarcAnthonyPhotography** [comment]
Thank you so much. This is really amazing. One question. How can I change or remove the compression of the video files. I want to have the videos saved in their original size and quality.

**Comment by lincf0912** [comment]
Can you tell me your iPad model? I have no this problem with using the iPad(the new pad) test, but I found some problems and fixed them. Would you please test again? thanks.
[ImagePicker2_videoEdit_1.zip](https://github.com/lincf0912/LFImagePickerController/files/1190101/ImagePicker2_videoEdit_1.zip)

**Comment by MarcAnthonyPhotography** [comment]
Thanks. I tried it but it is still throwing the same error as above. I am using an iPad Air 2 and iPad Pro 9.7. The error only occurs with slo-mo video.

**Comment by lincf0912** [comment]
The slow motion video is special. I've fixed it and remove the compression of the video files.
[ImagePicker2_videoEdit_2.zip](https://github.com/lincf0912/LFImagePickerController/files/1192840/ImagePicker2_videoEdit_2.zip)

**Comment by MarcAnthonyPhotography** [comment]
Please let me hire you. You shouldn't be doing these updates for me for free. I really appreciate your efforts and time you've spent. I would like to hire you for a couple more updates. Email me at marcanthonyphotography@gmail.com so we can set something up. Here's the remaining features I would like.

1. I would like to be able to hide options from the LFEditToolbar. For example, I may want to hide mosaic editing for photos so that it is only draw, stickers, text, crop. A simple way to enable it would be nice.

2. For slomotion video editing only, I would like to remove the audio from the video file and mix it with an audio file. Slow motion video recording on the iPad also records the sound but when you play it the sound is also slow. I would like to add some music to the video instead. The audio track would loop if it is shorter than the video file.

3. For the photo cropping menu I would like to have a cropping format selector so the user can choose to crop the image square. Manually cropping to square isn't always perfect or easy.

4. And last. There is a reason why I need to edit photos/video horizontally. My app only works in landscape. I know you said it would take too long but I have no problems paying you to do this. I understand if it can't be done. I just thought I would ask again. LOL.

Again, thank you for all of this. You are a truly great asset to the GitHub community.

**Comment by MarcAnthonyPhotography** [comment]
I lost the email you sent me. Let me know when you can handle this project

**Comment by lincf0912** [comment]
This project might take more time. Before the end of August. I'll try to finish by August 20th. (^_^)v

**Comment by lincf0912** [comment]
Did you receive my mail?

**Comment by MarcAnthonyPhotography** [comment]
I didn't but I am away on vacation until next Tuesday and don't have much internet

**Comment by lincf0912** [comment]
This project has been waiting for a long time. It's time to see the demo.
[ImagePicker20170803.zip](https://github.com/lincf0912/LFImagePickerController/files/1240513/ImagePicker20170803.zip)

**Comment by MarcAnthonyPhotography** [comment]
Got it. Thank you very much. I'll be away on vacation until next week so I won't be able to test until I get back but thank you for this. I'll let you know how it works

Cordially,
Marc A. Matteo
iSIT Kiosk
www.isitkiosk.com
856.981.3209

**Comment by lincf0912** [comment]
This project has been waiting for a long time. It's time to see the demo.
[ImagePicker20170803.zip](https://github.com/lincf0912/LFImagePickerController/files/1240513/ImagePicker20170803.zip)

**Comment by lincf0912** [comment]
Have a nice vacation!
